const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gcElectron', {
  compileLatex: (req) => ipcRenderer.invoke('latex:compile', req ?? {}),
  pickLatexProject: () => ipcRenderer.invoke('latex:pick-project'),
  listLatexProjectFiles: (req) => ipcRenderer.invoke('latex:list-project-files', req ?? {}),
  readLatexProjectFile: (req) => ipcRenderer.invoke('latex:read-project-file', req ?? {}),
  writeLatexProjectFile: (req) => ipcRenderer.invoke('latex:write-project-file', req ?? {}),
  synctexForward: (req) => ipcRenderer.invoke('latex:synctex-forward', req ?? {}),
  synctexInverse: (req) => ipcRenderer.invoke('latex:synctex-inverse', req ?? {}),
  storageGetWorkspaceSnapshot: () => ipcRenderer.invoke('storage:get-workspace-snapshot'),
  storagePutWorkspaceSnapshot: (req) => ipcRenderer.invoke('storage:put-workspace-snapshot', req ?? {}),
  storageDeleteWorkspaceSnapshot: () => ipcRenderer.invoke('storage:delete-workspace-snapshot'),
  storageGetChatStateRecord: (req) => ipcRenderer.invoke('storage:get-chat-state-record', req ?? {}),
  storagePutChatStateRecord: (req) => ipcRenderer.invoke('storage:put-chat-state-record', req ?? {}),
  storageDeleteChatStateRecord: (req) => ipcRenderer.invoke('storage:delete-chat-state-record', req ?? {}),
  storageGetChatMetaRecord: (req) => ipcRenderer.invoke('storage:get-chat-meta-record', req ?? {}),
  storagePutChatMetaRecord: (req) => ipcRenderer.invoke('storage:put-chat-meta-record', req ?? {}),
  storageDeleteChatMetaRecord: (req) => ipcRenderer.invoke('storage:delete-chat-meta-record', req ?? {}),
  storageGetPayload: (req) => ipcRenderer.invoke('storage:get-payload', req ?? {}),
  storagePutPayload: (req) => ipcRenderer.invoke('storage:put-payload', req ?? {}),
  storageDeletePayload: (req) => ipcRenderer.invoke('storage:delete-payload', req ?? {}),
  storagePutAttachment: (req) => ipcRenderer.invoke('storage:put-attachment', req ?? {}),
  storageGetAttachment: (req) => ipcRenderer.invoke('storage:get-attachment', req ?? {}),
  storageDeleteAttachment: (req) => ipcRenderer.invoke('storage:delete-attachment', req ?? {}),
  storageListAttachmentKeys: () => ipcRenderer.invoke('storage:list-attachment-keys'),
  storageDeleteAttachments: (req) => ipcRenderer.invoke('storage:delete-attachments', req ?? {}),
  storageClearAll: () => ipcRenderer.invoke('storage:clear-all'),
});
